-- Intentionally empty.
--
-- The MMMerge artifact system used to live here: baked stat/skill bonuses,
-- permanent buffs, effect immunities, attack-delay mods, flat HP/SP regen,
-- wear conditions, arrow sprites and on-hit effects.
--
-- Maw computes all of that itself and this file's version fought with it, so
-- it ships empty rather than deleted: the file must exist to overwrite the one
-- that comes with MMMerge.
--
-- Where each piece went:
--   stats and skills   -> artifactPower in General/zzMaw-Items.lua,
--                         priced by Modules/MawCore/Artifacts.lua
--   on-hit damage,
--   on-hit spells,
--   anti-type doubling,
--   vampirism (Mordred),
--   Cycle of Life,
--   Ethric's Staff     -> General/zzzMaw_Artifacts.lua
--   HP/SP regen        -> artifactHpRegen / artifactSpRegen in zzMaw-Items.lua,
--                         applied as a share of max HP/SP in zzMAW-Skills.lua
--   Game.CountItemBonuses -> stub in General/zzzMaw_Artifacts.lua, for the
--                         multiplayer sync that still calls it
